### DISCUSSION TITLE
Adding CMake flags

### DISCUSSION THREAD

**Discussion by viktorChekhovoi** [pyodide/pyodide#2039] [Q&A]
I'm trying to add the dlib package to pyodide, and I ran into an error that I believe can be resolved by adding some flags to the CMake command: 
```
-DCMAKE_CXX_COMPILE_FEATURES=cxx_constexpr -DCMAKE_CXX_FLAGS="-std=gnu++11"
```
Alternatively, the problem could also be solved by adding "cxxflags: -std=c++11" to meta.yaml (as suggested in issue #1475):
```
package:
  name: dlib
  version: 19.22.1

source:
  url: https://files.pythonhosted.org/packages/f0/a2/ba6163c09fb427990180afd8d625bcecc5555af699c253193c35ffd48c4f/dlib-19.22.1.tar.gz
  sha256: 77e943b40cc53e377d7fc683552d2337937f1111c46d7753105f594c3958163c

build:
  cxxflags: -std=c++11

test:
  imports:
    - dlib

```
Unfortunately, this didn't change the error output or the CMake command at all. I attached the error outputs below.
[output_with_cxxflags.txt](https://github.com/pyodide/pyodide/files/7704614/output_with_cxxflags.txt)
[output_without_cxxflags.txt](https://github.com/pyodide/pyodide/files/7704615/output_without_cxxflags.txt)

What's the best way to pass the flags to CMake or make the cxxflags work?
