### DISCUSSION TITLE
Build dependencies

### DISCUSSION THREAD

**Discussion by henryiii** [pyodide/pyodide#2167] [Q&A] [answered]
I'm working on building a package for boost-histogram. I actually was able to get it to build, but ran into a couple of issues along the way.

Most pressing: how do I add a build-time dependency - specifically, `setuptools_scm`? It seems to ignore my PEP 518 dependency specifications. I tried to add it to the `run:` table (which I'm guessing is really a `build:` dependency list? Shouldn't the normal `install_requires` be used from the wheel? Is it installed during the build process, at runtime, or both?), but that seems to require it be a recipe, which is unneeded for a pure Python wheel dependency. Without `setuptools_scm`, a package cannot read its included `version.py` file, so it is version 0.0.0. (Edit: https://github.com/pyodide/pyodide/pull/2132 looks like it would be helpful, still not sure about the PyPI pure wheel though)

Other examples of common build-time only dependencies are pybind11, Cython (usually, I think), and other build systems, like scikit-build. For binary packages, cmake & ninja possibly.

Second, I noticed a really weird issue where the pybind11 wasn't able to import itself inside the build process, even though it should have already been loaded in sys.modules. I'm not sure what might be interfering with that, and I'm happy to patch something if I need to, but it wasn't working. Manually skipping the self-include and including it fixes it, but I don't know why that is happening. Is anything special done here?

Finally, if I can clean it up, would you like me to make a PR with [boost-histogram](https://boost-histogram.readthedocs.io/en/latest/)? It's 672K.

PS: is there a way to try the wheel if I have it locally?

<details>
<summary>Recipe:</summary>

```yaml
package:
  name: boost-histogram
  version: 1.2.1
source:
  url: https://files.pythonhosted.org/packages/26/45/6cfc7f8a36aa9537dfbb4e3495180303ce98c3b1307c8bc8dfc3548e0507/boost_histogram-1.2.1.tar.gz
  sha256: a27842b2f1cfecc509382da2b25b03056354696482b38ec3c0220af0fc9b7579
  patches:
  - patches/incldir.patch
test:
  imports:
  - boost-histogram
requirements:
  run:
    - numpy # Not actually a build time requirement, could be dropped?
about:
  home: https://github.com/scikit-hep/boost-histogram
  PyPI: https://pypi.org/project/boost-histogram
  summary: The Boost::Histogram Python wrapper.
  license: BSD-3-Clause
```

</details>

<details>
<summary>Patch:</summary>

```
diff --git a/setup.cfg b/setup.cfg
index 2593e03..f8f23f5 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -1,5 +1,6 @@
 [metadata]
 name = boost_histogram
+version = 1.2.1
 description = The Boost::Histogram Python wrapper.
 long_description = file: README.md
 long_description_content_type = text/markdown
diff --git a/setup.py b/setup.py
index 7a88a83..308dbb1 100644
--- a/setup.py
+++ b/setup.py
@@ -28,6 +28,7 @@ SRC_FILES = [

 INCLUDE_DIRS = [
     "include",
+    "extern/pybind11/include",
     "extern/assert/include",
     "extern/config/include",
     "extern/core/include",
@@ -43,6 +44,7 @@ ext_modules = [
         SRC_FILES,
         include_dirs=INCLUDE_DIRS,
         cxx_std=cxx_std,
+        include_pybind11=False,
         extra_compile_args=["/d2FH4-"] if sys.platform.startswith("win32") else [],
     )
 ]
```

</details>

1.3.0 should be out very soon, and I think the include dir fix could go in. The version is a bigger issue.

Edit 2:

I ran into a few quirks testing it. I was able to start up the console.html, but I wasn't able to `micropip.install` boost-histogram, it claimed it needed to be pure Python. I then couldn't find anything useful on `pyodide`, like a `load*` function. But then I tried `micropip.install("hist")`, and that worked (boost-histogram is a dependency). Then I couldn't load hist (since I didn't have matplotlib build, and that's an _optional_ dependency, but for some reason pyodide insisted on loading the part with matplotlib), but I was able to import and use boost-histogram now!

<img width="758" alt="Screen Shot 2022-02-11 at 9 32 06 PM" src="https://user-images.githubusercontent.com/4616906/153695737-3882829e-e04a-411a-adef-b3c7ffac4935.png">

Is there any use to uploading the wheel anywhere, like to a GitHub release? Is there any way to run it without locally compiling pyodide?
