### DISCUSSION TITLE
How to link library against blas and lapack

### DISCUSSION THREAD

**Discussion by gabrielfougeron** [pyodide/pyodide#2201] [Q&A] [answered]
Hi,

I have built a python application, which I would like to deploy on a webpage. It seems to me like pyodide is perfect for that.

I've gone through the dependencies, and I've managed to remove all dependencies that are not currently supported by pyodide, except for a c/c++ library called "suitesparse", which I used via conda.

Yet, I've managed to take it out of my conda environment, build it from scratch and use it in my project.
I guess the next natural step is to start having it run in Pyodide, but I don't really know where to start.
This library (suitesparse) depends on Blas and Lapack, which might prove challenging, but is (I assume) not blocking, as I have the impression that you went through the trouble of dealing with them when integrating scipy.

So in fine, my question is: where to start?

PS: I am rather a newbie in terms of all this "deploy stuff", so don't assume much prior knowledge from me. I am however highly motivated to learn!

**Comment by hoodmane** [comment]
SuiteSparse looks very complex. The inclusion of Fortran can make life very hard, thankfully it seems like the Fortran is all Fortran 77, so it might be okay.

> where to start?

I would suggest that you start out by trying to build some of the libraries few dependencies and see if you can get the build working for them.  I might try building AMD. The easiest possible thing would be to `cd` into the directory and run `emmake make`. If this runs without error, then you have to look at what it produced and try to assess whether it is a useful `wasm32-emscripten` shared library. You can put your build script into a `packages/SuiteSparse/meta.yaml` file with something like:
```yaml
package:
  name: SuiteSparse
  version: 3.2.1

source:
  url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/refs/tags/v5.10.1.tar.gz

build:
  sharedlibrary: true
  script: |
    cd AMD
    emmake make
```

I suggest building it inside of our docker image with:
```sh
export PYTHONPATH='$PYTHONPATH:/src/pyodide-build/'
python3.9 -m pyodide_build buildpkg packages/SuiteSparse/meta.yaml
```

**Comment by gabrielfougeron** [comment]
Thank you very much for your input !
Here is what I did since yesterday : I removed all the parts of SuiteSparse that I did not need, and did manage to build with emmake. Everything successfully compiled, the only thing that failed was the final link with blas and lapack.

==> I don't know much about yaml, I'll look into it

I'm now building pyodide from scratch. I is extremely slow though (It's been at it for two hours). 
I'l then try to include my version of Suitesparse in the Pyodide packages and link with CLAPACK. 

I'll give you an update then.

Thanks again,

**Reply by hoodmane** [reply]
> ==> I don't know much about yaml, I'll look into it

This won't be a problem, yaml is very simple you can imitate the existing `meta.yaml` files.

> It is extremely slow though (It's been at it for two hours).

We have a prebuilt docker image, if you use that you shouldn't need to build Python. I've never used it myself but it seems like other people have had good experiences. 

> I removed all the parts of SuiteSparse that I did not need, and did manage to build with emmake. Everything successfully compiled, the only thing that failed was the final link with blas and lapack.

You are probably in good shape then. If you share information to reproduce what you've done up to this point I may look into the linking stage for you.

**Reply by gabrielfougeron** [reply]
Sure ! This stripped down version is available at https://github.com/gabrielfougeron/Choreographies2/tree/deploy_tests/SuiteSparse-master
. In this folder, just do "make", which should install to the local folder.

**Reply by rth** [reply]
> I is extremely slow though (It's been at it for two hours).

Yes, the pre-built docker image should help, as in particular it should include a pre-populated ccache cache. Only building the packages you need should make it faster. `PYODIDE_PACKAGES="<your-package>" make`

Also have a look at how CLAPACK is linked in https://github.com/pyodide/pyodide/blob/main/packages/scipy/meta.yaml though there are also several hacks to fix function signatures (that you might not need, not sure).

**Reply by hoodmane** [reply]
> Sure ! This stripped down version is available at [gabrielfougeron/Choreographies2@deploy_tests/SuiteSparse-master](https://github.com/gabrielfougeron/Choreographies2/tree/deploy_tests/SuiteSparse-master)
. In this folder, just do "make", which should install to the local folder.

I get the error:
```
CMake Error: The source directory ".../Choreographies2/SuiteSparse-master/metis-5.1.0" does not appear to contain CMakeLists.txt.
```

**Reply by gabrielfougeron** [reply]
@hoodmane : This is weird, I don't know how to explain this output. maybe you could try the other possibility I proposed in the post down below ... ?

**Comment by gabrielfougeron** [comment, marked as answer]
UPDATE : 
 I believe I have managed to build suitesparse inside pyodide with the following meta.yaml file:

```
package:
  name: suitesparse
  version: 1.0.0

source:
  sha256: eeb7af00bf9e7154d5e422eda73035ef58ecc41d2afa284dd697ca2c1ce04e7b
  url: https://gabrielfougeron.github.io/files/suitesparse.zip
  extract_dir: suitesparse

requirements:
  #build:
    #- CLAPACK
  run:
    - CLAPACK

build:
  sharedlibrary: true
  # set linker and C flags to error on anything to do with function declarations being wrong.
  # In webassembly, any conflicts mean that a randomly selected 50% of calls to the function
  # will fail. Better to fail at compile or link time.
  ldflags: |
    -Wl,--fatal-warnings
  script: |
    emmake make BLAS="-L/home/gfowsl/pyodide/packages/CLAPACK/dist/lib -lblas" LAPACK="-L/home/gfowsl/pyodide/packages/CLAPACK/dist/lib/ -llapack"
    mkdir -p dist/lib
    mkdir -p dist/include
    mkdir -p dist/bin
    cp -R bin/* dist/bin
    cp -R include/* dist/include
    cp -R lib/*  dist/lib
````
Un fortunately, I couldn't get rid of the hardcoded paths. $(PYODIDE_ROOT) did not seem to work there.

I also needed to add these two lines to the meta.yml in CLAPACK:

```
    emcc blas_WA.a -sSIDE_MODULE -o dist/lib/libblas.so
    emcc lapack_WA.a -sSIDE_MODULE -o dist/lib/liblapack.so
```

Again, any help / pointer is welcome.
