### DISCUSSION TITLE
Testing a Python package on Pyodide via GitHub Actions

### DISCUSSION THREAD

**Discussion by Kodiologist** [pyodide/pyodide#3462] [Q&A] [answered]
I maintain the [Hy](https://github.com/hylang/hy) programming language, which is essentially a Python package. It has a `pytest` test suite, which [we run on GitHub Actions](https://github.com/hylang/hy/blob/29b751d945a9abce475fcb81bfef03768f519572/.github/workflows/tests.yml). So far we've only officially supported CPython and PyPy. I can get the tests to pass on Pyodide with minor adjustments. I've run them on Firefox on my computer, looking at `pytest`'s output in the browser console. But I'd like to run the tests on Pyodide on GitHub Actions, too. Any ideas how to do this? Maybe with a headless web browser?

**Comment by hoodmane** [comment, marked as answer]
I think the easiest way is with the command line runner which tests against node. This has the advantage that the filesystem inside Pyodide is mostly the same as the true filesystem. See here for an introduction:
https://pyodide.org/en/stable/development/building-and-testing-packages.html#testing-packages-against-pyodide

**Reply by hoodmane** [reply]
At the bottom of that page I link the numpy Pyodide GitHub action which you can imitate but your case is slightly simpler because you have a pure Python package.

**Reply by Kodiologist** [reply]
Thanks, minor edits to the NumPy example seem to work well for Hy.

Are there any binaries of Pyodide for Node.js, or does one have to compile it every time with `pyodide-build`?

**Reply by hoodmane** [reply]
There are binaries. You can npm install it or use [pyodide-core-0.22.0.tar.bz2](https://github.com/pyodide/pyodide/releases/download/0.22.0/pyodide-core-0.22.0.tar.bz2) (which is supposed to be just the stuff you need for node).
Before pyodide v0.22 you should just npm install it.

**Reply by Kodiologist** [reply]
`npm install pyodide` appears to work fine, but not to make available a program `pyodide` in `PATH`, so the following fails with `pyodide: command not found`. Am I missing something? I have no experience with Node.js.

```yaml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-node@v3
- run: npm install pyodide
- name: Set up Pyodide virtual environment
  run: |
    pyodide venv .venv-pyodide
    source .venv-pyodide/bin/activate
    pip install .
    pip install pytest
- name: Test
  run: |
    source .venv-pyodide/bin/activate
    python -m pytest tests
```
