### DISCUSSION TITLE
Cmake can't find numpy

### DISCUSSION THREAD

**Discussion by pfebrer** [pyodide/pyodide#3780] [Q&A] [answered]
I'm trying to build the [`sisl`](https://github.com/zerothi/sisl) package in tree with the docker container, which uses `scikit-build-core` and `cmake`.

At this line in the main `CMakeLists.txt`:

```
find_package(Python COMPONENTS
  Interpreter
  Development.Module
  NumPy
  REQUIRED)
```

the build fails with the error:

```

cmake -DCMAKE_C_COMPILER=/tmp/tmp_5425z4d/cc -DCMAKE_CXX_COMPILER=/tmp/tmp_5425z4d/c++ -DCMAKE_AR=/tmp/tmp_5425z4d/ar -DCMAKE_C_COMPILER_AR=/tmp/tmp_5425z4d/ar -DCMAKE_CXX_COMPILER_AR=/tmp/tmp_5425z4d/ar --fresh -S. -Bbuild/cp311-cp311-emscripten_3_1_32_wasm32 -Cbuild/cp311-cp311-emscripten_3_1_32_wasm32/CMakeInit.txt -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON3_INCLUDE_PATH=/src/cpython/installs/python-3.11.3/include/python3.11 -DPYTHON3_LIBRARY=/src/cpython/installs/python-3.11.3/include/python3.11/../libpython3.11.a -DPYTHON3_VERSION_MAJOR=3 -DPYTHON3_VERSION_MINOR=11 -DNumPy_INCLUDE_DIR=/src/packages/.artifacts/lib/python3.11/site-packages/numpy//core/include -DNumPy_INCLUDE_DIRS=/src/packages/.artifacts/lib/python3.11/site-packages/numpy/core/include -DWITH_FORTRAN=OFF -DPYTHON3_NumPy_INCLUDE_DIR=/src/packages/.artifacts/lib/python3.11/site-packages/numpy/core/include -DPYTHON3_NumPy_INCLUDE_DIRS=/src/packages/.artifacts/lib/python3.11/site-packages/numpy/core/include -DCMAKE_CROSSCOMPILING_EMULATOR=/src/emsdk/emsdk/node/15.14.0_64bit/bin/node;--experimental-wasm-bulk-memory;--experimental-wasm-threads
loading initial cache file build/cp311-cp311-emscripten_3_1_32_wasm32/CMakeInit.txt
-- Building with CMake version: 3.26.3
-- Building with scikit-build-core: 0.3.1
CMake Error at /usr/local/lib/python3.11/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python (missing: Python_NumPy_INCLUDE_DIRS Interpreter
  Development.Module NumPy) (found version "3.11.3")
Call Stack (most recent call first):
  /usr/local/lib/python3.11/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/lib/python3.11/site-packages/cmake/data/share/cmake-3.26/Modules/FindPython.cmake:622 (find_package_handle_standard_args)
  CMakeLists.txt:23 (find_package)
```

I'm confused because if you look at the cmake arguments it seems the numpy include directory was passed correctly.

This is my `meta.yaml`:

```yaml
package:
  name: sisl
  version: 0.13.0
  top-level:
          #- sisl_toolbox
    - sisl
source:
  url: https://github.com/zerothi/sisl/archive/refs/heads/main.zip
  sha256: 1292a69b63857614948097b4a6ff724f88ec86894cc8ff577a8f16bb697bb9d3
  patches:
    - patches/remove_fortran.patch

about:
  home: ""
  PyPI: https://pypi.org/project/sisl
  summary: ""
  license: MPL-2.0


requirements:
  host:
    - numpy
    - pyparsing
  run:
    - pyparsing
    - numpy
    - scipy
    - tqdm
    #- netcdf4

build:
    script: |
      source $PKGDIR/cmake/build_args.sh
```

which includes a patch to remove the fortran language in `patches/remove_fortran`:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b4411bcae..860d41bd1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -9,7 +9,7 @@ endif()
 project(sisl
   DESCRIPTION "Cythonized or fortran codes"
   HOMEPAGE_URL "https://github.com/zerothi/sisl"
-  LANGUAGES C CXX Fortran
+  LANGUAGES C CXX
   # cmake requires a version of X.Y.Z or some other form, it does not accept setuptools_scm dirty tags
   #  VERSION "${SKBUILD_PROJECT_VERSION}"
   )
```

And a script to define the CMAKE arguments in `cmake/build_args.sh`:

```bash
#!/bin/bash

export NUMPY_INCLUDE_DIR="${NUMPY_LIB}/core/include"

export CMAKE_ARGS=" \
-DPYTHON3_INCLUDE_PATH=$PYTHONINCLUDE \
-DPYTHON3_LIBRARY=$PYTHONINCLUDE/../libpython$PYMAJOR.$PYMINOR.a \
-DPYTHON3_VERSION_MAJOR=$PYMAJOR \
-DPYTHON3_VERSION_MINOR=$PYMINOR \
-DNumPy_INCLUDE_DIR=$NUMPY_INCLUDE_DIR \
-DNumPy_INCLUDE_DIRS=$NUMPY_INCLUDE_DIR \
-DWITH_FORTRAN=OFF \
-DPYTHON3_NumPy_INCLUDE_DIR=$NUMPY_INCLUDE_DIR \
-DPYTHON3_NumPy_INCLUDE_DIRS=$NUMPY_INCLUDE_DIR \
"
```

Any hint on what's happening? Thanks :pray: :pray:
