### DISCUSSION TITLE
"No such file or directory" error when executing python code using created pyodide package

### DISCUSSION THREAD

**Discussion by LijieZhang1998** [pyodide/pyodide#4074] [Q&A] [answered]
Hi, I followed this [instruction](https://pyodide.org/en/latest/development/new-packages.html#building-a-python-package-in-tree) to create a `pymongo` pyodide package. The following is meta.yaml file for building `pymongo` package. As `pymongo` depends on `dnspython`, I also built `dnspython` package. 

<details open>
 <summary>meta.yaml</summary>

```
package:
  name: pymongo
  version: 4.4.1
  top-level:
    - bson
    - gridfs
    - pymongo
source:
  url: https://files.pythonhosted.org/packages/bf/1c/38b956d48667745f2f083937dd31b0467fa3f537480e30c692b1fc4fef3d/pymongo-4.4.1.tar.gz
  sha256: a4df87dbbd03ac6372d24f2a8054b4dc33de497d5227b50ec649f436ad574284
requirements:
  run:
    - dnspython
about:
  home: http://github.com/mongodb/mongo-python-driver
  PyPI: https://pypi.org/project/pymongo
  summary: Python driver for MongoDB <http://www.mongodb.org>
  license: Apache License, Version 2.0
```
</details>

When I ran my ping.js code, I got an error `PythonError: Traceback (most recent call last): File "/lib/python3.11/site-packages/dns/resolver.py", line 992, in read_resolv_conf  
cm: contextlib.AbstractContextManager = open(f)
FileNotFoundError: [Errno 44] No such file or directory: '/etc/resolv.conf'
`
Any idea about how I can address this issue? Thank you. 
<details>
  <summary>ping.js</summary>

```js
const test = function () {
  const { loadPyodide } = require("pyodide");
  async function hello_python() {
    let pyodide = await loadPyodide();
    await pyodide.loadPackage("ssl");
    await pyodide.loadPackage("pymongo");
    const src = `
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
    
# Replace the placeholder with your Atlas connection string
uri = "..." 

# Set the Stable API version when creating a new client
client = MongoClient(uri, server_api=ServerApi('1'))
                              
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)`;
    return pyodide.runPythonAsync(src);
  }
  hello_python().then((result) => {
    console.log("Python says that 1+1 =", result);
  });
};

test();

```

</details>
