### DISCUSSION TITLE
Best practice to only include `pyodide-py` in non-emscripten environments

### DISCUSSION THREAD

**Discussion by CNSeniorious000** [pyodide/pyodide#4769] [Q&A] [answered]
I have a package which currently depends on `pyodide`/`pyodide-py`'s `pyodide.code.eval_code_async`. But there is no need to install `pyodide-py` in emscripten runtime. So I need to specify it in `pyproject.toml`.

So which one is better?

```toml
[project]
dependencies = [
  "pyodide-py~=0.26.0a4 ; platform_system != 'Emscripten'",
]
```

Or

```toml
[project]
dependencies = [
  "pyodide-py~=0.26.0a4 ; sys_platform != 'emscripten'",
]
```
