### DISCUSSION TITLE
Out of tree build for meta.yaml package using GitHub Actions

### DISCUSSION THREAD

**Discussion by johnwason** [pyodide/pyodide#4976] [Q&A]
I am having some trouble using `pyodide-build` with a GitHub Action for a native library using cmake and a meta.yaml recipe. I think we have discussed this before but things have changed so I am not sure my understanding is up to date.

I have this workflow file in a test repository:

```yaml
name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
    
jobs:
  build-pyodide:
    runs-on: ubuntu-22.04
    env:
      EMSDK_NUM_CORES: 3
      EMCC_CORES: 3
      PYODIDE_JOBS: 3
      #CCACHE_DIR: /tmp/dep-ccache
    steps:
    - uses: actions/checkout@v4
      with:
        path: rr_src
        repository: robotraconteur/robotraconteur
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y build-essential libboost-all-dev zlib1g-dev libssl-dev libdbus-1-dev libbluetooth-dev libusb-1.0-0-dev
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - run: |
        pip install "pyodide-build>=0.23.0" "numpy<2.0"
        echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ env.EMSCRIPTEN_VERSION }}
    - name: build pregenerated_src
      run: |
        cmake -S $GITHUB_WORKSPACE/rr_src -B gen_src -DPACKAGE_SWIG_SOURCE_ALL=ON -DBUILD_PYTHON3=ON -DBUILD_TESTING=OFF
        cmake --build gen_src --config Release --target package_source_swig
        cp -r $GITHUB_WORKSPACE/gen_src/generated_src $GITHUB_WORKSPACE/rr_src/
        sudo cmake --build gen_src --config Release --target install -j4
        sudo python -m pip install $GITHUB_WORKSPACE/gen_src/out/Python3
    - run: pyodide build-recipes .
      working-directory: rr_src/tools/build_files/pyodide
```

https://github.com/johnwason/github-actions-scratch/blob/5ea35552e57de4d7e34ef78bca645d037e926203/.github/workflows/main.yml

Upstream: https://github.com/robotraconteur/robotraconteur

Recipe: https://github.com/robotraconteur/robotraconteur/tree/master/tools/build_files/pyodide

The workflow output for this version is here: https://github.com/johnwason/github-actions-scratch/actions/runs/10171385207/job/28132247480

I am getting this error:

```
Run pyodide build-recipes .
Downloading xbuild environment                                                  
Installing xbuild environment                                                   
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pyodide_ │
│ build/cli/build_recipes.py:88 in recipe                                      │
│                                                                              │
│    85 │   n_jobs = n_jobs or get_num_cores()                                 │
│    86 │                                                                      │
│    87 │   if not recipe_dir_.is_dir():                                       │
│ ❱  88 │   │   raise FileNotFoundError(f"Recipe directory {recipe_dir_} not f │
│    89 │                                                                      │
│    90 │   build_args = pywasmcross.BuildArgs(                                │
│    91 │   │   cflags=cflags,                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: Recipe directory 
/home/runner/work/github-actions-scratch/github-actions-scratch/rr_src/tools/bui
ld_files/pyodide/packages not found
Error: Process completed with exit code 1.
```

**Comment by ryanking13** [comment]
> python-version: 3.11

You'll probably need to use 3.12 as the latest Pyodide uses 3.12, and host Python version should match.

> pyodide build-recipes .

You can pass `--recipe-dir` to set the base recipe directory. The recipe directory should have the following directory structure.

```
<recipe_dir>
╰ robotraconteur
    ╰ meta.yaml
```

and calling `pyodide build-recipes --recipe-dir <recipe_dir> robotraconteur` would build robotraconteur

**Comment by johnwason** [comment]
I have made some progress, but am still getting an error. Here is my new workflow:

```yaml
name: CI

on:
  push:
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:
    
jobs:
  build-pyodide:
    runs-on: ubuntu-22.04
    env:
      EMSDK_NUM_CORES: 3
      EMCC_CORES: 3
      PYODIDE_JOBS: 3
      #CCACHE_DIR: /tmp/dep-ccache
    steps:
    - uses: actions/checkout@v4
      with:
        path: rr_src
        repository: robotraconteur/robotraconteur
    - uses: actions/checkout@v4
      with:
        repository: pyodide/pyodide
        path: src
    # - name: ccache deps
    #   uses: actions/cache@v3
    #   with:
    #     path: |
    #       /tmp/dep-ccache
    #     key: pyodide-deps-${{ hashFiles('Makefile.envs') }}
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y build-essential libboost-all-dev zlib1g-dev libssl-dev libdbus-1-dev libbluetooth-dev libusb-1.0-0-dev tree
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - run: |
        pip install "pyodide-build>=0.23.0" "numpy<2.0"
        echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ env.EMSCRIPTEN_VERSION }}
    - name: build pregenerated_src
      run: |
        cmake -S $GITHUB_WORKSPACE/rr_src -B gen_src -DPACKAGE_SWIG_SOURCE_ALL=ON -DBUILD_PYTHON3=ON -DBUILD_TESTING=OFF
        cmake --build gen_src --config Release --target package_source_swig
        cp -r $GITHUB_WORKSPACE/gen_src/generated_src $GITHUB_WORKSPACE/rr_src/
        sudo cmake --build gen_src --config Release --target install -j4
        sudo python -m pip install $GITHUB_WORKSPACE/gen_src/out/Python3
    - run: |
        mkdir -p $GITHUB_WORKSPACE/p/recipes/RobotRaconteur
        cp -v $GITHUB_WORKSPACE/rr_src/tools/build_files/pyodide/* $GITHUB_WORKSPACE/p/recipes/RobotRaconteur
        tree $GITHUB_WORKSPACE/p
        tree $GITHUB_WORKSPACE/rr_src/tools/build_files
    - run: pyodide build-recipes --recipe-dir $GITHUB_WORKSPACE/src/packages numpy boost-cpp
    - run: pyodide build-recipes --recipe-dir $GITHUB_WORKSPACE/p/recipes RobotRaconteur
```

Now I am getting this error:

```
Run pyodide build-recipes --recipe-dir $GITHUB_WORKSPACE/src/packages numpy boost-cpp
  
xbuild environment already exists, skipping download                            
Installing xbuild environment                                                   
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pyodide_ │
│ build/recipe.py:[18](https://github.com/johnwason/github-actions-scratch/actions/runs/10187356063/job/28181198075#step:10:18) in load_all_recipes                                       │
│                                                                              │
│    15 │   recipes: dict[str, MetaConfig] = {}                                │
│    16 │   for recipe in recipes_path:                                        │
│    17 │   │   try:                                                           │
│ ❱  [18](https://github.com/johnwason/github-actions-scratch/actions/runs/10187356063/job/28181198075#step:10:19) │   │   │   config = MetaConfig.from_yaml(recipe)                      │
│    [19](https://github.com/johnwason/github-actions-scratch/actions/runs/10187356063/job/28181198075#step:10:20) │   │   │   recipes[config.package.name] = config                      │
│    [20](https://github.com/johnwason/github-actions-scratch/actions/runs/10187356063/job/28181198075#step:10:21) │   │   except Exception as e:                                         │
│    21 │   │   │   raise ValueError(f"Could not parse {recipe}.") from e      │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pyodide_ │
│ build/io.py:179 in from_yaml                                                 │
│                                                                              │
│   176 │   │   stream = path.read_bytes()                                     │
│   177 │   │   config_raw = yaml.safe_load(stream)                            │
│   178 │   │                                                                  │
│ ❱ 179 │   │   config = cls(**config_raw)                                     │
│   180 │   │   if config.source.path:                                         │
│   181 │   │   │   config.source.path = path.parent / config.source.path      │
│   182 │   │   return config                                                  │
│                                                                              │
│ in pydantic.main.BaseModel.__init__:341                                      │
╰──────────────────────────────────────────────────────────────────────────────╯
ValidationError: 1 validation error for MetaConfig
extra
  extra fields not permitted (type=value_error.extra)
The above exception was the direct cause of the following exception:
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pyodide_ │
│ build/cli/build_recipes.py:118 in recipe                                     │
│                                                                              │
│   115 │   │   else:                                                          │
│   116 │   │   │   targets = ",".join(packages)                               │
│   117 │   │                                                                  │
│ ❱ 118 │   │   pkg_map = buildall.build_packages(                             │
│   119 │   │   │   recipe_dir_, targets, build_args, n_jobs, force_rebuild    │
│   120 │   │   )                                                              │
│   1[21](https://github.com/johnwason/github-actions-scratch/actions/runs/10187356063/job/28181198075#step:10:22)                                                                        │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pyodide_ │
│ build/buildall.py:753 in build_packages                                      │
│                                                                              │
│   750 │   force_rebuild: bool = False,                                       │
│   751 ) -> dict[str, BasePackage]:                                           │
│   752 │   requested, disabled = _parse_package_query(targets)                │
│ ❱ 753 │   requested_packages = recipe.load_recipes(packages_dir, requested)  │
│   754 │   pkg_map = generate_dependency_graph(                               │
│   755 │   │   packages_dir, set(requested_packages.keys()), disabled         │
│   756 │   )                                                                  │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pyodide_ │
│ build/recipe.py:53 in load_recipes                                           │
│                                                                              │
│    50 │   │   Dictionary of package name => config                           │
│    51 │   """                                                                │
│    52 │                                                                      │
│ ❱  53 │   available_recipes = load_all_recipes(recipe_dir)                   │
│    54 │                                                                      │
│    55 │   # tag => list of recipes with that tag                             │
│    56 │   tagged_recipes: dict[str, list[MetaConfig]] = {}                   │
│                                                                              │
│ /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/pyodide_ │
│ build/recipe.py:21 in load_all_recipes                                       │
│                                                                              │
│    18 │   │   │   config = MetaConfig.from_yaml(recipe)                      │
│    19 │   │   │   recipes[config.package.name] = config                      │
│    20 │   │   except Exception as e:                                         │
│ ❱  21 │   │   │   raise ValueError(f"Could not parse {recipe}.") from e      │
│    [22](https://github.com/johnwason/github-actions-scratch/actions/runs/10187356063/job/28181198075#step:10:23) │                                                                      │
│    [23](https://github.com/johnwason/github-actions-scratch/actions/runs/10187356063/job/28181198075#step:10:24) │   return recipes                                                     │
│    [24](https://github.com/johnwason/github-actions-scratch/actions/runs/10187356063/job/28181198075#step:10:25)                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: Could not parse 
/home/runner/work/github-actions-scratch/github-actions-scratch/src/packages/pys
am/meta.yaml.
```

**Comment by ryanking13** [comment]
```
      with:
        python-version: 3.11
    - run: |
        pip install "pyodide-build>=0.23.0" "numpy<2.0"
```

Please use python 3.12 and pyodide-build >= 0.26, which is compatible with last version of Pyodide and recipes.


```
    - run: pyodide build-recipes --recipe-dir $GITHUB_WORKSPACE/src/packages numpy boost-cpp
    - run: pyodide build-recipes --recipe-dir $GITHUB_WORKSPACE/p/recipes RobotRaconteur
```

you need to put the recipes in the same directory, I would not suggesting cloning pyodide/pyodide and using recipes from it because we are planning to remove recipes from the repository (#4918), Please copy related recipes and store them in your own repository.
