### ISSUE TITLE
PKG Add jax

### ISSUE THREAD

**Issue by rth** [pyodide/pyodide#2198]
Looking at the list of dependencies [jax](https://github.com/google/jax) should be easier to build than torch or tensorflow #50, and it would be useful to include it.

**Comment by horaceg** [comment]
Being able to have demos of JAX ML models running in the browser would be truly amazing !

**Comment by josephrocca** [comment]
Question: Given that the `jaxlib` repo is in a sub-folder within the `jax` github repo, and that `jaxlib` isn't a standalone pypi package, I'm assuming that I should be setting `build.library:true` in the `meta.yaml`, but the build instructions for `jaxlib` are simply:

```bash
# install requirements:
sudo apt-get update
sudo apt-get install -y python3-dev
pip install numpy wheel
# build CPU-only jaxlib:
python build/build.py
pip install dist/*.whl  # installs jaxlib (includes XLA)
```

And that's a bit confusing because all the build scripts for other `build.library:true` use `emconfigure` and `emmake` directly ([example](https://github.com/pyodide/pyodide/blob/main/packages/libxml/meta.yaml)), whereas in this case it seems like we just want to use `python build/build.py` but with all the build tools "swapped out" with emscripten versions, just like when building a normal package. So that makes me think that maybe I shouldn't be using `build.library:true`.

But my problem is that in `build.script`, the build tooling haven't been swapped out for the emscripten versions, so I'm not sure how to run this:
```
python build/build.py
pip install dist/*.whl  # installs jaxlib (includes XLA)
```
in such a way that it's all built with emscripten.

Some resources in case it's useful:
* https://github.com/conda-forge/jaxlib-feedstock/blob/main/recipe/meta.yaml
* https://github.com/conda-forge/jax-feedstock/blob/main/recipe/meta.yaml

For `install_requires`, `jaxlib` just has:
```
['scipy', 'numpy>=1.19', 'absl-py', 'flatbuffers >= 1.12, < 3.0']
```
and for `jax` itself:
```
install_requires=['absl-py','numpy>=1.19','opt_einsum','scipy>=1.2.1','typing_extensions','etils[epath]']
```
But as of a few days ago the jax team is [removing the absl-py requirement](https://github.com/google/jax/pull/10968) (making it optional).

`opt_einsum.contract` seems to be an API-compatible sped-up version of `numpy.einsum` (if I'm reading [this](https://pypi.org/project/opt-einsum/) correctly), so that sounds like it might be easy to swap out for now.

I'm not sure what `typing_extensions` and `etils[epath]` are for. These might cause some trouble?

CC @hoodmane

**Comment by hoodmane** [comment]
You certainly shouldn't be setting `library: true` because that's for static libraries. We might need to expand the build system a bit for this one. You could hypothetically build `libjax` in the `build.script`, this happens before the package itself is built. But in that case you need to ensure that libjax uses emcc with all the proper config.

**Comment by josephrocca** [comment]
Yeah I was wondering if there's a way to trigger the swap to the emscripten tools before running `build.script` rather than after? That said I don't really know how the whole build pipeline fits together. I tried this (doing `emmake`/`emcc`/etc. symlinking in `built.script`):

<details>
  <summary>meta.yaml</summary>

```yaml
package:
  name: jax
  version: 0.3.13
source:
  url: https://github.com/google/jax/archive/refs/tags/jax-v0.3.13.tar.gz
  sha256: d7ea74f8fd4ee69698f7350078f7987fe66333a0ac84b057dc792aa72b5f1813

build:
  script: |
    # install requirements:
    sudo apt-get update
    sudo apt-get install -y python3-dev
    pip install numpy wheel
    # build CPU-only jaxlib:
    mkdir -p /src/symlink-tools
    ln -sf "$(which emcc)" /src/symlink-tools/gcc
    ln -sf "$(which emmake)" /src/symlink-tools/make
    ln -sf "$(which emconfigure)" /src/symlink-tools/configure
    export PATH="/src/symlink-tools:$PATH"
    python build/build.py
    pip install dist/*.whl  # installs jaxlib (includes XLA)

test:
  imports:
    - jax
about:
  home: https://github.com/google/jax
  PyPI: https://pypi.org/project/jax
  summary: Differentiate, compile, and transform Numpy code.
  license: Apache-2.0
```
Results in this error when running `python -m pyodide_build buildpkg meta.yaml`:

```
...
...
...
Building XLA and installing it in the jaxlib source tree...
./bazel-5.1.1-linux-x86_64 run --verbose_failures=true --config=avx_posix --config=mkl_open_source_only :build_wheel -- --output_path=/src/packages/jax/build/jax-0.3.13/dist --cpu=x86_64
b''
Traceback (most recent call last):
  File "/src/packages/jax/build/jax-0.3.13/build/build.py", line 528, in <module>
    main()
  File "/src/packages/jax/build/jax-0.3.13/build/build.py", line 523, in main
    shell(command)
  File "/src/packages/jax/build/jax-0.3.13/build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bazel-5.1.1-linux-x86_64', 'run', '--verbose_failures=true', '--config=avx_posix', '--config=mkl_open_source_only', ':build_wheel', '--', '--output_path=/src/packages/jax/build/jax-0.3.13/dist', '--cpu=x86_64']' returned non-zero exit status 1.
```
</details>

But that gives an error as shown in the above folded section. It builds fine if I leave out the symlink stuff ([yaml and full logs here](https://gist.github.com/josephrocca/db203fd42fb46f9fb83420f7bb68375c)), but obviously the resulting wheel wouldn't work in Pyodide because emscripten wasn't involved in the compilation. I'm guessing that the above error is at least partly because `buildpkg` does more than just symlink the emscripten versions of the build tools - at least going by this comment in the `compile` function in `pyodide_build/buildpkg.py`:

> Runs pywasmcross for the package. The effect of this is to first run setup.py with compiler wrappers subbed in, which don't actually build the package but write the compile commands to build.log. Then we walk over build log and invoke the same set of commands but with some flags munged around or removed to make it work with emcc.

Is there anything that I could investigate/"prod at" here as a newbie? If someone (with some more experience/understanding of this stuff) could provide a high level dot-point plan that they think is the best approach, that would be super useful!
