### ISSUE TITLE
Trying to add new package: REBOUND

### ISSUE THREAD

**Issue by hannorein** [pyodide/pyodide#2864]
## 🐍 Package Request

- Package Name and Version: **rebound/latest**
- Package URL: [https://github.com/hannorein/rebound](https://github.com/hannorein/rebound)
- Package Dependencies that needs to be resolved first: None

I'm trying to make the REBOUND package compatible with pyodide but I'm stuck. I've followed the instructions in the documentation and I seem to get through all the steps without any error messages. I can see that all the c files get compiled and in the end, I see a `Succeeded building package rebound` message and a `whl` file. However, upon closer inspection, the `.so` file seems to be empty. On the other hand, I've checked the `.o` files which seem to be ok. So maybe there is a problem with the linking? Given the lack of error messages, any help on how to proceed would be greatly appreciated.

**Comment by ryanking13** [comment]
Could you open a draft PR so that we can see the log and output files?

**Comment by jobovy** [comment]
Do you have the `meta.yaml` that you are using? Maybe you need to add
```
build:
  exports: "requested"
```
to the `meta.yaml`. WIth that, I can build `rebound` in `pyodide` and run your "Python Version" example [here](https://rebound.readthedocs.io/en/latest/quickstart_firstexample/). This is running in a `pyodide` REPL that has `rebound` here: https://astro.utoronto.ca/~bovy/pyodide/dist/console.html. Note that you have to monkey-patch `_multiprocessing` as explained at https://github.com/pyodide/pyodide/issues/1603 to be able to import `rebound` (you would have to patch `rebound` or release a new version that avoids importing `_multiprocessing` to avoid this).

My `rebound` `meta.yaml` for reference:
```
package:
  name: rebound
  version: 3.19.3
source:
  url: https://files.pythonhosted.org/packages/c8/78/ef900196c683c0bc51b1c71738\
65d9016a45eb10339b2b8d737c5c77acbc/rebound-3.19.3.tar.gz
  sha256: 8f97e6b1238d68c72783bd55206c030ca6dfdd4c034f8dd976cc5bd22f521eb1
build:
  exports: "requested"
test:
  imports:
    - rebound
about:
  home: https://github.com/hannorein/rebound/
  PyPI: https://pypi.org/project/rebound
  summary: An open-source multi-purpose N-body code
  license: GPL
```
