### ISSUE TITLE
Add `brotli` package

### ISSUE THREAD

**Issue by MuTsunTsai** [pyodide/pyodide#2921]
## 🐍 Package Request

- Package Name and Version : brotli 1.0.9
- Package URL : https://github.com/google/brotli, https://pypi.org/project/brotli
- Package Dependencies that needs to be resolved first: none

I'm new to pyodide and I followed the docs to use `pyodide_build mkpkg` (which is quite difficult to get it to work on Windows, by the way). It gives me the following meta.yaml:

```
package:
  name: brotli
  version: 1.0.9
source:
  url: https://files.pythonhosted.org/packages/2a/18/70c32fe9357f3eea18598b23aa9ed29b1711c3001835f7cf99a9818985d0/Brotli-1.0.9.zip
  sha256: 4d1b810aa0ed773f81dceda2cc7b403d01057458730e309856356d4ef4188438
test:
  imports:
  - brotli
about:
  home: https://github.com/google/brotli
  PyPI: https://pypi.org/project/brotli
  summary: Python bindings for the Brotli compression library
  license: MIT
```

I'm not sure if I should add anything. And I'm a bit confused that running `pyodide_build buildpkg` doesn't really generate anything other than an empty build.log file. Since I have no idea if I'm doing it right, I suppose I'll just put a request here. Thanks!
