### ISSUE TITLE
Add `PyMuPDF` package

### ISSUE THREAD

**Issue by Splines** [pyodide/pyodide#4701]
## 🐍 Package Request

> PyMuPDF is a high performance Python library for data extraction, analysis, conversion & manipulation of PDF (and other) documents. ~ From the project description on [PyPI](https://pypi.org/project/PyMuPDF/)

- Package Name and Version : `PyMuPDF / latest` (currently: `1.24.1`)
- Package URL : [PyPI](https://pypi.org/project/PyMuPDF/), [Docs](https://pymupdf.readthedocs.io/en/latest/index.html), [GitHub](https://github.com/pymupdf/PyMuPDF?tab=readme-ov-file)
- Package Dependencies that need to be resolved first: See the package list [here](https://github.com/pymupdf/PyMuPDF/blob/main/setup.py#L1165-L1189) (they programatically add strings to their `pyproject.toml` depending on the config settings. Note that PyMuPDF is a wrapper for [MuPDF](https://mupdf.com/) (written in C)

**Comment by KevenDev** [comment]
> Algo assim funcionou para mim
> 
> git clone https://github.com/pymupdf/PyMuPDF.git
> cd PyMuPDF
> pixi init
> pixi add python=3.12.*
> pixi shell
> git clone https://github.com/emscripten-core/emsdk.git emsdk
> python3.12 -m venv venv_pyodide_3.12 
> . venv_pyodide_3.12/bin/activate
> python -m pip install --upgrade pip wheel pyodide-build==0.29.3 
> cd emsdk 
> export PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) 
> ./emsdk install ${PYODIDE_EMSCRIPTEN_VERSION} 
> ./emsdk activate ${PYODIDE_EMSCRIPTEN_VERSION} 
> . ./emsdk_env.sh 
> cd ..
> SKIP_EMSCRIPTEN_VERSION_CHECK=1 EMCC_DEBUG=1 HAVE_LIBCRYPTO=no OS=pyodide PYMUPDF_SETUP_FLAVOUR=pb PYMUPDF_SETUP_MUPDF_BUILD_TESSERACT=0 PYMUPDF_SETUP_MUPDF_TESSERACT=0 pyodide build --exports whole_archive




Did this work for a javascript environment? If so, how did you do it? Could you explain better?

**Comment by linuxrider** [comment]
I'm not sure I understand your question. Do you mean 
> `for a javascript environment` 
as e.g. running in browser?

**Comment by sanzoghenzo** [comment]
Hi, pyodide noob here!

I would like to share a marimo notebook that uses pyMuPDF to wasm, so this request is spot on for me.

I see that the pymudf project already has [instructions on how to build the wheel](https://pymupdf.readthedocs.io/en/latest/pyodide.html#building-a-pymupdf-wheel-for-pyodide) and a [pipeline that builds the wheel daily](https://github.com/pymupdf/PyMuPDF/blob/main/.github/workflows/test_pyodide.yml).

The script used by the pipeline is essentially what @linuxrider posted.

Can we leverage upstream build script to incorporate the package here somehow, or do we need to adapt the script to make it in-tree?

**Comment by hoodmane** [comment]
Well you can always use the wheel that PyMuPDF is building. But if you want to add it to the Pyodide distribution, we'll need our own recipe.

**Comment by sanzoghenzo** [comment]
> Well you can always use the wheel that PyMuPDF is building

the wheel is inside an archive in the artifacts section of github, accessible only by registered users, so it will render my notebook not so shareable... indeed I could just download it and save it alongside the notebook... but I believe this package would be a great addition to pyodide registry, so let's try to add it!

I tried to translate the script above into a recipe, if I interpreted it correctly we only need to set the `build.export` attribute and pass the environment variables to the build chain... I tried to use `backend-flags`, but it seems that it ignores them and tries to build the package with tesseract enabled

```yaml
# packages/pymupdf/meta.yaml
package:
  name: pymupdf
  version: 1.25.4
  top-level:
    - pymupdf
    - fitz
source:
  url: https://files.pythonhosted.org/packages/25/56/d7de0325125621a3d095eb43ce35f2e036cd4c0489ff5e8cae816f1cd8b9/pymupdf-1.25.4.tar.gz
  sha256: 5f189466b68901055a9ddc77dc1c91cba081a60964f0caa6ff5b9b87001a0194
about:
  home: https://pymupdf.readthedocs.io
  PyPI: https://pypi.org/project/pymupdf
  summary:
    A high performance Python library for data extraction, analysis, conversion
    & manipulation of PDF (and other) documents.
  license: Dual Licensed - GNU AFFERO GPL 3.0 or Artifex Commercial License

build:
  exports: whole_archive
  backend-flags: |
    HAVE_LIBCRYPTO=no
    OS=pyodide
    PYMUPDF_SETUP_FLAVOUR=pb
    PYMUPDF_SETUP_MUPDF_BUILD_TESSERACT=0
    PYMUPDF_SETUP_MUPDF_TESSERACT=0
```

I always had a hard time with compilation tools, so I might miss something obvious, but does anybody have a clue on how to properly build this package?

[Here you can find the log output](https://pastebin.com/iCRHZP0m)
