### ISSUE TITLE
Compiling C++ package fails with libc compiled without fPIC

### ISSUE THREAD

**Issue by juntyr** [pyodide/pyodide#5250]
## 🐛 Bug

I'm trying to build the `healpy` package. Compilation of its C++ code fails during linking with the following errors:

```
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(ofl.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `ofl_lock`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(ofl.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `ofl_head`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(ofl.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `ofl_lock`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(__errno_location.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `__errno_storage`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `states`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.1`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `xdigits`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_TABLE_INDEX_SLEB cannot be used against symbol `fmt_fp`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_TABLE_INDEX_SLEB cannot be used against symbol `pop_arg_long_double`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.3`; recompile with -fPIC
wasm-ld: error: /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a(vfprintf.o): relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `.L.str.3`; recompile with -fPIC
```

### To Reproduce

The meta.yaml file I've got so far is:

```yaml
package:
  name: healpy
  version: 1.18.0
  top-level:
    - healpy
source:
  url: https://files.pythonhosted.org/packages/7f/d2/239fb1bd8b75049bae1a64152d22108400fa4aba06859f3199935646c36f/healpy-1.18.0.tar.gz
  sha256: 6a12fd8f804c8a6d193dc43d1dcdf636808830e1ccc0aa7c53d83e394bb15289
requirements:
  run:
    - numpy
    - astropy
    - matplotlib
    - scipy
  executable:
    - gfortran
build:
  cflags: |
    -DgFortran
    -I$(WASM_LIBRARY_DIR)/include
    -fPIC
  cxxflags: |
    -fPIC
  ldflags: |
    -fPIC
  script: |
    set -x
    git clone https://github.com/hoodmane/f2c.git --depth 1
    (cd f2c/src && cp makefile.u makefile && sed -i "s/gram.c:/gram.c1:/" makefile && make)
    export F2C_PATH=$(pwd)/f2c/src/f2c
about:
  home: https://github.com/healpy/healpy
  PyPI: https://pypi.org/project/healpy
  summary: Healpix tools package for Python
  license: GPL-2.0-only
```

I tried adding `-fPIC` as a flag everywhere but that doesn't seem to help.

### Expected behavior

Continue compiling ... until the next issue shows up (or none)

### Environment

- Pyodide Version: 0.27.0.dev0
- Browser version: NA
- Any other relevant information: NA

- Commit hash of Pyodide git repository: https://github.com/climet-eu/pyodide/tree/climet-lab-0.27.0, which builds on top of 4967029933ba120e0a320f21f6c2b0b736b5cdfd
- Build environment

Thanks for #5231 for helping with building Fortran code!

**Comment by juntyr** [comment]
I've narrowed the failure down to the last command:

```
/src/emsdk/emsdk/upstream/bin/wasm-ld -o .libs/libhealpix_cxx.so.4.0.5 cxxsupport/.libs/announce.o cxxsupport/.libs/geom_utils.o cxxsupport/.libs/string_utils.o cxxsupport/.libs/ls_image.o cxxsupport/.libs/paramfile.o cxxsupport/.libs/pointing.o cxxsupport/.libs/rotmatrix.o cxxsupport/.libs/trafos.o cxxsupport/.libs/walltimer.o cxxsupport/.libs/wigner.o cxxsupport/.libs/error_handling.o cxxsupport/.libs/fitshandle.o Healpix_cxx/.libs/alm.o Healpix_cxx/.libs/alm_healpix_tools.o Healpix_cxx/.libs/alm_powspec_tools.o Healpix_cxx/.libs/healpix_tables.o Healpix_cxx/.libs/healpix_base.o Healpix_cxx/.libs/healpix_map.o Healpix_cxx/.libs/powspec.o Healpix_cxx/.libs/moc_query.o Healpix_cxx/.libs/weight_utils.o Healpix_cxx/.libs/mask_tools.o Healpix_cxx/.libs/alice3.o Healpix_cxx/.libs/healpix_data_io.o Healpix_cxx/.libs/healpix_map_fitsio.o Healpix_cxx/.libs/alm_fitsio.o Healpix_cxx/.libs/powspec_fitsio.o Healpix_cxx/.libs/moc_fitsio.o -L/src/packages/healpy/build/healpy-1.18.0/build/temp.emscripten_3_1_58_wasm32-cpython-312/lib /src/packages/healpy/build/healpy-1.18.0/build/temp.emscripten_3_1_58_wasm32-cpython-312/lib/libsharp.so /src/packages/healpy/build/healpy-1.18.0/build/temp.emscripten_3_1_58_wasm32-cpython-312/lib/libcfitsio.so -L/src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libGL-getprocaddr.a -lal -lhtml5 -lstubs -lnoexit -lc /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libdlmalloc.a -lcompiler_rt /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc++-noexcept.a /src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc++abi-noexcept.a -lsockets --fatal-warnings -L/src/cpython/installs/python-3.12.1/lib/ -L/src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-memory --strip-debug --export=__wasm_call_ctors --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export-if-defined=__start_em_lib_deps --export-if-defined=__stop_em_lib_deps --export-if-defined=__start_em_js --export-if-defined=__stop_em_js --export-if-defined=__wasm_apply_data_relocs --experimental-pic --unresolved-symbols=import-dynamic -shared --no-export-dynamic
```

which seems to link the non-pic sysroot. If I manually edit the command so that all sysroot paths are changed from `-L/src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten` to `-L/src/emsdk/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/pic` and I replace the `-noexcept` variants with the variants with exceptions (and compile with `-fexceptions`), that huge command succeeds.

How do I make the linker command automatically pick the pic sysroot with exceptions?

**Comment by juntyr** [comment]
@dicej I think you worked stumbled across a similar error when working on shared library support for wasi-sdk - do you have any ideas?

**Comment by dicej** [comment]
> @dicej I think you worked stumbled across a similar error when working on shared library support for wasi-sdk - do you have any ideas?

I just updated the `wasi-libc` Makefile to pass `-fPIC` to the compiler when building the code.  Originally, I did that unconditionally, but folks expressed concern that the indirection overhead of `-fPIC` would pessimize the libc.a build for those who don't need it, so I ended up building two separate sets of .o files: one with `-fPIC` (for libc.so) and one without (for libc.a): https://github.com/WebAssembly/wasi-libc/blob/29c22a4b68545868028a537e6c5f7f678d80aa82/Makefile#L629.

**Comment by juntyr** [comment]
The sysroot does contain libc with pic in a separate subfolder but I'm not sure how to tell emcc to use just it (and not the default non-PIC versions).

**Comment by juntyr** [comment]
I tried adding this flag to cflags, cxxflags, and ldflags but the error remained

**Comment by juntyr** [comment]
> Could you try adding `-sRELOCATABLE=1` flag? It affects how emscripten locates the libraries ([ref](https://github.com/emscripten-core/emscripten/blob/c08204e56de44a66763ed58c161622850b1da91a/tools/cache.py#L125-L126))

Ok, you were onto the solution! I got compilation to work and the package now seems to work as well. Here's the final YAML file

```yaml
package:
  name: healpy
  version: 1.18.0
  top-level:
    - healpy
source:
  url: https://files.pythonhosted.org/packages/7f/d2/239fb1bd8b75049bae1a64152d22108400fa4aba06859f3199935646c36f/healpy-1.18.0.tar.gz
  sha256: 6a12fd8f804c8a6d193dc43d1dcdf636808830e1ccc0aa7c53d83e394bb15289
requirements:
  run:
    - numpy
    - astropy
    - matplotlib
    - scipy
  executable:
    - gfortran
build:
  cflags: |
    -DgFortran
    -I$(WASM_LIBRARY_DIR)/include
  script: |
    set -x
    git clone https://github.com/hoodmane/f2c.git --depth 1
    (cd f2c/src && cp makefile.u makefile && sed -i "s/gram.c:/gram.c1:/" makefile && make)
    export F2C_PATH=$(pwd)/f2c/src/f2c
  cross-script: |
    export CXXFLAGS="$CXXFLAGS -sRELOCATABLE=1"
about:
  home: https://github.com/healpy/healpy
  PyPI: https://pypi.org/project/healpy
  summary: Healpix tools package for Python
  license: GPL-2.0-only
```

Interestingly, I had to set `-sRELOCATABLE=1` in the cross-script and couldn't use the cxxflags setting.
